# -*- coding: utf-8 -*-
"""encrypt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b98JT7MJYtCyv1TqnE3Y8dh7VHX6UsXH
"""

import cv2
import os
import numpy as np
from google.colab import files
from PIL import Image

def upload_image():
    """Uploads an image in Google Colab and returns its file path."""
    uploaded = files.upload()
    image_path = list(uploaded.keys())[0]  # Get the first uploaded file
    return image_path

def encrypt_image(image_path, msg, password, output_path="encryptedImage.jpg"):
    """Embeds a secret message into an image."""
    img = cv2.imread(image_path)
    if img is None:
        print("Error: Could not read image.")
        return

    d = {chr(i): i for i in range(255)}

    n, m, z = 0, 0, 0

    for char in msg:
        img[n, m, z] = d[char]
        n += 1
        m += 1
        z = (z + 1) % 3

    cv2.imwrite(output_path, img)
    print(f"Encryption successful! Image saved as {output_path}")
    return password

if __name__ == "__main__":
    print("Please upload an image:")
    image_path = upload_image()  # Allow user to upload an image

    msg = input("Enter secret message: ")
    password = input("Enter a passcode: ")
    encrypt_image(image_path, msg, password)